"""initial models

Revision ID: 8838de1b67a1
Revises: 
Create Date: 2026-09-08 22:54:01.194154

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8838de1b67a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_instagram_handle'), 'competitor', ['instagram_handle'], unique=False)
    op.create_index(op.f('ix_competitor_website_url'), 'competitor', ['website_url'], unique=False)
    op.create_table('contentplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawledsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawledsource_source_type'), 'crawledsource', ['source_type'], unique=False)
    op.create_index(op.f('ix_crawledsource_source_url'), 'crawledsource', ['source_url'], unique=True)
    op.create_table('instagrampost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PostOwnerType', sa.Enum('OWN', 'COMPETITION', name='postownertype'), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashtags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commentsCount', sa.Integer(), nullable=False),
    sa.Column('likesCount', sa.Integer(), nullable=False),
    sa.Column('videoViewCount', sa.Integer(), nullable=False),
    sa.Column('displayUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('altText', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('childPosts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagrampost_engagement_score'), 'instagrampost', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_instagrampost_owner_username'), 'instagrampost', ['owner_username'], unique=False)
    op.create_table('websitedatachunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websitedatachunks_owner'), 'websitedatachunks', ['owner'], unique=False)
    op.create_index(op.f('ix_websitedatachunks_source_file'), 'websitedatachunks', ['source_file'], unique=False)
    op.create_table('websitedataembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['websitedatachunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websitedataembedding_chunk_id'), 'websitedataembedding', ['chunk_id'], unique=False)
    # NOTE: keep langchain_pg_* tables for backward compat — do not drop
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websitedataembedding_chunk_id'), table_name='websitedataembedding')
    op.drop_table('websitedataembedding')
    op.drop_index(op.f('ix_websitedatachunks_source_file'), table_name='websitedatachunks')
    op.drop_index(op.f('ix_websitedatachunks_owner'), table_name='websitedatachunks')
    op.drop_table('websitedatachunks')
    op.drop_index(op.f('ix_instagrampost_owner_username'), table_name='instagrampost')
    op.drop_index(op.f('ix_instagrampost_engagement_score'), table_name='instagrampost')
    op.drop_table('instagrampost')
    op.drop_index(op.f('ix_crawledsource_source_url'), table_name='crawledsource')
    op.drop_index(op.f('ix_crawledsource_source_type'), table_name='crawledsource')
    op.drop_table('crawledsource')
    op.drop_table('contentplan')
    op.drop_index(op.f('ix_competitor_website_url'), table_name='competitor')
    op.drop_index(op.f('ix_competitor_instagram_handle'), table_name='competitor')
    op.drop_table('competitor')
    # ### end Alembic commands ###
